version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.CrmSdk.XrmTooling.WpfControls
    versions:
    - 9.1.0.68
    - 9.1.0.77
  - dependency-name: Microsoft.CrmSdk.XrmTooling.CoreAssembly
    versions:
    - 9.1.0.68
    - 9.1.0.77
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: MSTest.TestFramework
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: Microsoft.CrmSdk.Workflow
    versions:
    - 9.0.2.32
  - dependency-name: Microsoft.CrmSdk.Deployment
    versions:
    - 9.0.2.32
  - dependency-name: Microsoft.CrmSdk.CoreAssemblies
    versions:
    - 9.0.2.32
  - dependency-name: MscrmTools.Xrm.Connection
    versions:
    - 1.2021.1.39
  - dependency-name: xrmtb.XrmToolBox.Controls
    versions:
    - 2.2.9
  - dependency-name: XrmToolBoxPackage
    versions:
    - 1.2020.12.43
